[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-Mokshakl4k
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-Mokshakl4k
GtkTheme=oomox-Mokshakl4k
IconTheme=oomox-Mokshakl4k
MetacityTheme=oomox-Mokshakl4k
